//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.29 at 04:26:19 PM ICT 
//


package com.ipmugo.articleservice.schema.openarchives.oai.oai_marc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.openarchives.org/OAI/1.1/oai_marc}fixfield" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.openarchives.org/OAI/1.1/oai_marc}varfield" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="level" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ctlType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="charEnc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="encLvl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="catForm" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="lrRqrd" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fixfield",
    "varfield"
})
@XmlRootElement(name = "oai_marc")
public class OaiMarc {

    @XmlElement(required = true)
    protected List<Fixfield> fixfield;
    protected List<Varfield> varfield;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "level", required = true)
    protected String level;
    @XmlAttribute(name = "ctlType")
    protected String ctlType;
    @XmlAttribute(name = "charEnc")
    protected String charEnc;
    @XmlAttribute(name = "encLvl")
    protected String encLvl;
    @XmlAttribute(name = "catForm")
    protected String catForm;
    @XmlAttribute(name = "lrRqrd")
    protected String lrRqrd;

    /**
     * Gets the value of the fixfield property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fixfield property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFixfield().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Fixfield }
     * 
     * 
     */
    public List<Fixfield> getFixfield() {
        if (fixfield == null) {
            fixfield = new ArrayList<Fixfield>();
        }
        return this.fixfield;
    }

    /**
     * Gets the value of the varfield property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the varfield property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVarfield().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Varfield }
     * 
     * 
     */
    public List<Varfield> getVarfield() {
        if (varfield == null) {
            varfield = new ArrayList<Varfield>();
        }
        return this.varfield;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the ctlType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtlType() {
        return ctlType;
    }

    /**
     * Sets the value of the ctlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtlType(String value) {
        this.ctlType = value;
    }

    /**
     * Gets the value of the charEnc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharEnc() {
        return charEnc;
    }

    /**
     * Sets the value of the charEnc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharEnc(String value) {
        this.charEnc = value;
    }

    /**
     * Gets the value of the encLvl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncLvl() {
        return encLvl;
    }

    /**
     * Sets the value of the encLvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncLvl(String value) {
        this.encLvl = value;
    }

    /**
     * Gets the value of the catForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatForm() {
        return catForm;
    }

    /**
     * Sets the value of the catForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatForm(String value) {
        this.catForm = value;
    }

    /**
     * Gets the value of the lrRqrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrRqrd() {
        return lrRqrd;
    }

    /**
     * Sets the value of the lrRqrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrRqrd(String value) {
        this.lrRqrd = value;
    }

}
