//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.29 at 04:26:19 PM ICT 
//


package com.ipmugo.articleservice.schema.openarchives.oai.oai_marc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openarchives.oai._1_1.oai_marc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openarchives.oai._1_1.oai_marc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OaiMarc }
     * 
     */
    public OaiMarc createOaiMarc() {
        return new OaiMarc();
    }

    /**
     * Create an instance of {@link Fixfield }
     * 
     */
    public Fixfield createFixfield() {
        return new Fixfield();
    }

    /**
     * Create an instance of {@link Varfield }
     * 
     */
    public Varfield createVarfield() {
        return new Varfield();
    }

    /**
     * Create an instance of {@link Subfield }
     * 
     */
    public Subfield createSubfield() {
        return new Subfield();
    }

}
