//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.29 at 04:26:19 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openarchives.org/OAI/1.1/oai_marc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ipmugo.articleservice.schema.openarchives.oai.oai_marc;
